### ISSUE TITLE
No data received

### ISSUE THREAD

**Issue by scruffian** [tzachz/github-comment-counter#10]
When I run the command to launch the server, everything seems to work fine, I have something running at http://localhost:8081, but at http://localhost:8080/ it just says "No data received".

```
0:0:0:0:0:0:0:1 - - [07/Apr/2015:21:32:24 +0000] "GET / HTTP/1.1" 200 414 1 1
0:0:0:0:0:0:0:1 - - [07/Apr/2015:21:32:37 +0000] "GET / HTTP/1.1" 200 414 1 1
0:0:0:0:0:0:0:1 - - [07/Apr/2015:21:33:46 +0000] "GET / HTTP/1.1" 200 414 0 0
0:0:0:0:0:0:0:1 - - [07/Apr/2015:21:33:47 +0000] "GET /metrics?pretty=true HTTP/1.1" 200 12965 4 4
0:0:0:0:0:0:0:1 - - [07/Apr/2015:21:33:54 +0000] "GET / HTTP/1.1" 200 414 1 1
```

Any clue what I am doing wrong?

**Comment by tzachz** [comment]
There's one limitation I know of that isn't mentioned in the README (I'll add it) - you can't use a user with Two-Factor Authentication enabled (for obvious reasons) - might that be the case?

If not - can you send the yml snippet containing the GitHub credentials (with obfuscated password, of course) and organization name? Should be something like:

```
gitHubCredentials:
    username: tzachz
    password: <notgonnatellyou>

organization: kenshoo
```

Alternatively, assuming this is some issue with the organization you used, try setting some known organization with public activity, e.g. "netflix" which I've just tried and works well. 

Another option - if you see any error in the log (at ./logs/leaderboard-server.log), send it over.

**Comment by scruffian** [comment]
I did have 2fa on, but it seems to pull the data fine using an application specific password. I tried disabling 2fa, and I get the same result.

The issue doesn't seem to be in fetching the data, which works fine, it's about getting the server at port 8080 to launch. There is no `./logs` directory.

**Comment by tzachz** [comment]
@scruffian - I've been trying to nail this, with no success. 
Perhaps the issue is with the "default root": "/" should redirect to "/service/leaderboard/week" automatically, maybe that's what's failing. Can you try and see if http://localhost:8080/service/leaderboard/week does work?

**Comment by scruffian** [comment]
Nothing there, sorry :(

Let me know what else I can do to try to debug...

**Comment by tzachz** [comment]
Well, I'm pretty lost on this one, so I'll just write down anything that comes to mind, in the hope that something will pop up:
 - Did you try different browsers (I dunno, maybe some add-on is being naughty..)?
 - Maybe try using a simple wget or curl?
 - You can try debugging the application in an IDE:
    - Run the main in com.tzachz.commentcounter.server,LeaderBoardService with "server <path-to-yml>" program arguments
    - Put a breakpoint at com.tzachz.commentcounter.server.LeaderBoardResource:40 - each request for root url should be routed to that method
    - Let me know if you get there or not when you visit http://localhost:8080/
 - Try http://localhost:8080/service/leaderboard/week/json which returns the json representation of the same page, maybe there's some weird problem with the HTML rendering using template

That's all I've got... :confused:

**Comment by scruffian** [comment]
Is there a way to access the raw data without the server running? Or a way to change the port?

**Comment by tzachz** [comment]
Oh, you know what - I think I got it. Please add this to your yml file:
```
http:
    rootPath: /service/*
```
If that's the issue - well, sorry for the hassle... I'll start by adding it to the README or supplying a default yml to use (I thought I'd done that, now I see I didn't). Later on I'll try to simplify the yml.
If this still doesn't work and you want to try the port change, it's in the same yml clause:
```
http:
    rootPath: /service/*
    port: 8088  # or whatever..
```

**Comment by scruffian** [comment]
Whooooo!

Moving it to a new port worked :+1: 

Thanks so much for all your help. Now lets see if we can use it...
