### ISSUE TITLE
No support for API access via OAuth tokens

### ISSUE THREAD

**Issue by mquander** [tzachz/github-comment-counter#11]
A nicer way to access the GitHub API is by making an [OAuth token](https://developer.github.com/v3/auth/#via-oauth-tokens) with the privileges of your choosing and then passing that instead of a username and password.

Benefits:

- It's a less scary credential to put on your disk in the config file (because it's limited and revocable)
- It will work just fine for two-factor auth users

It's easy to support this; I'll have a PR available shortly for it.

**Comment by tzachz** [comment]
solved by #12
