### ISSUE TITLE
getting no main manifest attribute.

### ISSUE THREAD

**Issue by bitshadow** [tzachz/github-comment-counter#19]
After I building from source it generates `leaderboard-server-0.1.undef.jar` which is generating `undef` in version number also when I run this command
`$java -jar leaderboard-server-0.1.undef.jar server leaderboard-server.yml`

It shows this messages 
`no main manifest attribute, in leaderboard-server-0.1.undef.jar`.

Any idea what is happening here? And how can I fix it?

**Comment by tzachz** [comment]
Oh - looks like the README is wrong, the 'build' task doesn't create the **fatjar**, just the regular jar (missing the dependencies and the manifest). Please run this command instead:
```
./gradlew clean fatjar
```
You should then see a much larger `leaderboard-server-0.1.undef.jar` (~9M) which should have the correct manifest. Let me know if it solves the issue - sorry for the inconvenience anyway.

I'll fix the README.
As for the "undef" - it's not an issue, but I admit it's ugly... I'll try fixing that too.

**Comment by bitshadow** [comment]
That worked. Thank you @tzachz :)

One more thing. Github api endpoint (in GithubResource.java) can be different for private Organizations. Is it possible to make it more configurable like adding it in the yml file so that they can directly use it with released jar files.

Should I file another issue for that or here is fine?

**Comment by tzachz** [comment]
Good to hear! 
I'm not sure what you mean about GithubResource - I'm using it with a private organization with the current implementation. Let's indeed discuss it over a separate issue :)

**Comment by bitshadow** [comment]
Sure I will file another issue with proper description.

Thank you :+1:
