### ISSUE TITLE
Github API endpoint should be configurable.

### ISSUE THREAD

**Issue by bitshadow** [tzachz/github-comment-counter#20]
For private organizations/companies, there is different endpoint for Github hosted inside VPN. For example we have `https://github.corp.xyzcompany.com/api/v3/` 

In here https://github.com/tzachz/github-comment-counter/blob/3543eec091039616c8a3b02c6cdfe30c616b4e8b/github-comment-fetcher/src/main/java/com/tzachz/commentcounter/apifacade/GitHubResource.java#L22

Api end point is hardcoded. Can it be configurable via leaderboard-server.yml file?

Let me know if more information required.

**Comment by tzachz** [comment]
Oh - understood. Shouldn't be too hard, I'll try to implement it sometime this week.

**Comment by tzachz** [comment]
Resolved by #25
