### ISSUE TITLE
Some links point to github.com when using hosted github

### ISSUE THREAD

**Issue by lev112** [tzachz/github-comment-counter#26]
thanks for you hard work on this tool.

when running the server with a hosted githum (ie, setting `gitHubApiUrl`), some link are still pointing to github.com:
- the link to the organization on the top
- the link on the user names in the leader board

**Comment by tzachz** [comment]
@lev112 Thanks for your comment! 
Yeah, I guess I missed that! I'll see how soon I can fix this, would probably be a while before I get to it but fix itself should be simple.

**Comment by tzachz** [comment]
@lev112 should be fixed (try [release 0.1.1](https://github.com/tzachz/github-comment-counter/releases/tag/V0.1.1)), please let me know if you see issues. Thanks again!
