### ISSUE TITLE
Comment text is broken in Web page. 

### ISSUE THREAD

**Issue by avatar80** [tzachz/github-comment-counter#35]
hi!
The korean text comment is broken in web browser. 
What should I do if I want to use it with korean language?

**Comment by tzachz** [comment]
Thanks for reporting this! I see the issue, the resource is not properly specifying the charset in the content type, I'll issue a fix shortly.

**Comment by tzachz** [comment]
Fixed by #36 

@avatar80 feel free to try latest release, this should work now. Thanks again for reporting the issue

**Comment by avatar80** [comment]
Thank you very much for your prompt response. Your code is very helpful to our team. Thanks again!
